// ============================================================
// CITY SIGNS — PRODUCT CATALOG DATA
// Edit this file to add, remove, or update products.
// ============================================================

const PRODUCTS = [
  // ── BANNERS ─────────────────────────────────────────────
  {
    id: "ban-001",
    name: "13oz Vinyl Banner",
    category: "Banners",
    subcategory: "Vinyl Banners",
    description: "Durable 13oz vinyl banner for indoor and outdoor use. Full color printing with vibrant results.",
    tags: ["Outdoor", "Popular", "Custom"],
    sizes: ["24\"×36\"","2'×4'","2'×6'","2'×8'","3'×6'","3'×8'","4'×8'","4'×10'","5'×10'","Custom"],
    materials: ["13oz Vinyl"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Hem & Grommets", "Pole Pockets", "Rope", "Webbing & D-rings", "Reinforced Corners", "Windslits", "Velcro"],
    gradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    icon: "🏷️",
    isNew: false,
    isFeatured: true
  },
  {
    id: "ban-002",
    name: "18oz Blockout Banner",
    category: "Banners",
    subcategory: "Vinyl Banners",
    description: "Heavy-duty 18oz blockout vinyl banner. Prevents light bleed-through for bold, opaque results.",
    tags: ["Outdoor", "Heavy Duty"],
    sizes: ["2'×4'","2'×6'","3'×6'","3'×8'","4'×8'","Custom"],
    materials: ["18oz Blockout Vinyl"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Hem & Grommets", "Pole Pockets", "Rope", "Webbing & D-rings", "Reinforced Corners", "Windslits"],
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #2d5986 100%)",
    icon: "🚩",
    isNew: false,
    isFeatured: false
  },
  {
    id: "ban-003",
    name: "Mesh Banner",
    category: "Banners",
    subcategory: "Vinyl Banners",
    description: "Perforated mesh banner allows wind to pass through. Ideal for fences, scaffolding, and outdoor events.",
    tags: ["Outdoor", "Wind Resistant"],
    sizes: ["3'×6'","4'×8'","5'×10'","Custom"],
    materials: ["Mesh Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Hem & Grommets", "Rope", "Reinforced Corners", "Windslits"],
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    icon: "🌬️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "ban-004",
    name: "Fabric Banner (9oz)",
    category: "Banners",
    subcategory: "Fabric Banners",
    description: "Lightweight 9oz fabric banner with soft texture. Great for indoor events and retail environments.",
    tags: ["Indoor", "Fabric", "Event"],
    sizes: ["2'×4'","2'×6'","3'×6'","3'×8'","Custom"],
    materials: ["9oz Fabric"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Hem & Grommets", "Pole Pockets", "Velcro"],
    gradient: "linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)",
    icon: "🎪",
    isNew: false,
    isFeatured: false
  },
  {
    id: "ban-005",
    name: "Blockout Fabric Banner",
    category: "Banners",
    subcategory: "Fabric Banners",
    description: "Opaque fabric banner with blockout layer for double-sided printing without bleed-through.",
    tags: ["Indoor", "Fabric", "Double Sided"],
    sizes: ["2'×4'","3'×6'","4'×8'","Custom"],
    materials: ["Blockout Fabric"],
    sides: ["Double Sided"],
    finishing: ["Hem & Grommets", "Pole Pockets", "Velcro"],
    gradient: "linear-gradient(135deg, #be185d 0%, #9d174d 100%)",
    icon: "🎨",
    isNew: false,
    isFeatured: false
  },
  {
    id: "ban-006",
    name: "Pole Banner Set",
    category: "Banners",
    subcategory: "Pole Banners",
    description: "Street pole banner sets for municipalities, campuses, and shopping districts. Includes hardware.",
    tags: ["Outdoor", "Popular", "Event"],
    sizes: ["18\"×36\"","24\"×48\"","24\"×60\"","30\"×72\"","Custom"],
    materials: ["13oz Vinyl", "9oz Fabric"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Pole Pockets", "Hem & Grommets"],
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    icon: "🏙️",
    isNew: false,
    isFeatured: true
  },
  {
    id: "ban-007",
    name: "Backlit Banner",
    category: "Banners",
    subcategory: "Specialty Banners",
    description: "Translucent backlit banner film for lightboxes and illuminated displays. Vivid backlit colors.",
    tags: ["Indoor", "Backlit", "Trade"],
    sizes: ["Custom"],
    materials: ["Backlit Film"],
    sides: ["Single Sided"],
    finishing: ["Hem", "Grommets", "Pole Pockets"],
    gradient: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    icon: "💡",
    isNew: false,
    isFeatured: false
  },
  {
    id: "ban-008",
    name: "Hand Banner",
    category: "Banners",
    subcategory: "Specialty Banners",
    description: "Double-sided hand-held banners on a stick. Perfect for events, rallies, and promotions.",
    tags: ["Event", "Indoor", "Outdoor"],
    sizes: ["12\"×18\"","18\"×24\"","Custom"],
    materials: ["13oz Vinyl", "9oz Fabric"],
    sides: ["Double Sided"],
    finishing: ["Wooden Stick", "Plastic Stick"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #14532d 100%)",
    icon: "✋",
    isNew: true,
    isFeatured: false
  },

  // ── BANNER STANDS ────────────────────────────────────────
  {
    id: "bs-001",
    name: "Standard Retractable Banner Stand",
    category: "Banner Stands",
    subcategory: "Retractable Stands",
    description: "Classic pull-up retractable banner stand. Easy setup, lightweight, and portable.",
    tags: ["Trade", "Event", "Popular"],
    sizes: ["23\"×66\"","24\"×81\"","33\"×81\"","47\"×81\""],
    materials: ["Vinyl Print"],
    sides: ["Single Sided"],
    finishing: ["Carry Bag Included"],
    gradient: "linear-gradient(135deg, #475569 0%, #1e293b 100%)",
    icon: "📐",
    isNew: false,
    isFeatured: false
  },
  {
    id: "bs-002",
    name: "Deluxe Retractable Banner Stand",
    category: "Banner Stands",
    subcategory: "Retractable Stands",
    description: "Premium retractable stand with heavy-duty base. Available double-sided.",
    tags: ["Trade", "Event", "Premium"],
    sizes: ["33\"×81\"","33\"×81\" Double Sided"],
    materials: ["Vinyl Print"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Padded Carry Bag"],
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    icon: "🏆",
    isNew: false,
    isFeatured: false
  },
  {
    id: "bs-003",
    name: "Tension Fabric Stand",
    category: "Banner Stands",
    subcategory: "Fabric Stands",
    description: "Sleek tension fabric banner stand with pillow-case style graphic. Wrinkle-resistant.",
    tags: ["Trade", "Event", "Fabric"],
    sizes: ["36\"×90\"","48\"×90\""],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided"],
    finishing: ["Carry Bag"],
    gradient: "linear-gradient(135deg, #0891b2 0%, #0e7490 100%)",
    icon: "🎯",
    isNew: false,
    isFeatured: false
  },
  {
    id: "bs-004",
    name: "X-Stand Banner Stand",
    category: "Banner Stands",
    subcategory: "X-Stands",
    description: "Lightweight X-frame stand for cost-effective display solutions.",
    tags: ["Event", "Budget Friendly"],
    sizes: ["24\"×63\"","32\"×71\""],
    materials: ["Vinyl Print", "Fabric Print"],
    sides: ["Single Sided"],
    finishing: ["Carry Bag"],
    gradient: "linear-gradient(135deg, #854d0e 0%, #713f12 100%)",
    icon: "❌",
    isNew: false,
    isFeatured: false
  },
  {
    id: "bs-005",
    name: "Step and Repeat Backdrop",
    category: "Banner Stands",
    subcategory: "Backdrops",
    description: "Professional step-and-repeat backdrop for events, press walls, and photo opportunities.",
    tags: ["Event", "Popular", "Custom"],
    sizes: ["8'×8'","10'×8'","12'×8'","20'×8'","Custom"],
    materials: ["13oz Vinyl", "Fabric"],
    sides: ["Single Sided"],
    finishing: ["Adjustable Stand", "Carry Bag"],
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    icon: "📸",
    isNew: false,
    isFeatured: false
  },
  {
    id: "bs-006",
    name: "Table Top Banner Stand",
    category: "Banner Stands",
    subcategory: "Table Top Displays",
    description: "Compact tabletop retractable stand for counter and table displays.",
    tags: ["Trade", "Indoor"],
    sizes: ["11.5\"×17.5\""],
    materials: ["Vinyl Print"],
    sides: ["Single Sided"],
    finishing: ["Stand Included"],
    gradient: "linear-gradient(135deg, #065f46 0%, #064e3b 100%)",
    icon: "🖥️",
    isNew: true,
    isFeatured: false
  },

  // ── FLAGS ────────────────────────────────────────────────
  {
    id: "flg-001",
    name: "Feather Flag",
    category: "Flags",
    subcategory: "Advertising Flags",
    description: "Eye-catching feather-shaped advertising flag. Available in multiple sizes with base options.",
    tags: ["Outdoor", "Popular", "Advertising"],
    sizes: ["Small 9ft","Medium 10.5ft","Large 14ft","X-Large 18ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Cross Base","Ground Stake","Square Base","Water Bag"],
    gradient: "linear-gradient(135deg, #dc2626 0%, #991b1b 100%)",
    icon: "🏴",
    isNew: false,
    isFeatured: false
  },
  {
    id: "flg-002",
    name: "Teardrop Flag",
    category: "Flags",
    subcategory: "Advertising Flags",
    description: "Distinctive teardrop-shaped flag that stays taut in any wind condition.",
    tags: ["Outdoor", "Advertising"],
    sizes: ["Small 7ft","Medium 9ft","Large 11.2ft","XL 13.5ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Cross Base","Ground Stake","Square Base","Water Bag"],
    gradient: "linear-gradient(135deg, #d97706 0%, #b45309 100%)",
    icon: "💧",
    isNew: false,
    isFeatured: false
  },
  {
    id: "flg-003",
    name: "Rectangle Flag",
    category: "Flags",
    subcategory: "Advertising Flags",
    description: "Traditional rectangular advertising flag with maximum print area for messaging.",
    tags: ["Outdoor", "Advertising"],
    sizes: ["Small 8.5ft","Medium 11.8ft","Large 15ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Cross Base","Ground Stake","Square Base","Water Bag"],
    gradient: "linear-gradient(135deg, #15803d 0%, #14532d 100%)",
    icon: "🚩",
    isNew: false,
    isFeatured: false
  },
  {
    id: "flg-004",
    name: "Custom Pole Flag",
    category: "Flags",
    subcategory: "Pole Flags",
    description: "Full-color custom pole flags for businesses, schools, and organizations.",
    tags: ["Outdoor", "Custom"],
    sizes: ["2'×3'","3'×5'","4'×6'","5'×8'","Custom"],
    materials: ["Dye Sub Fabric", "Nylon"],
    sides: ["Single Sided", "Double Sided"],
    finishing: ["Grommets","Header & Grommets","Sleeve"],
    gradient: "linear-gradient(135deg, #7e22ce 0%, #581c87 100%)",
    icon: "🏳️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "flg-005",
    name: "Econo Feather Flag",
    category: "Flags",
    subcategory: "Advertising Flags",
    description: "Budget-friendly econo feather flag. One size at 16ft. Great for grand openings.",
    tags: ["Outdoor", "Budget", "Advertising"],
    sizes: ["One Size 16ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided"],
    finishing: ["Cross Base","Ground Stake"],
    gradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    icon: "💨",
    isNew: true,
    isFeatured: false
  },

  // ── TENTS ────────────────────────────────────────────────
  {
    id: "tent-001",
    name: "10x10 Aluminum Event Tent",
    category: "Tents",
    subcategory: "Event Tents",
    description: "Complete 10x10 aluminum tent with dye sub canopy. Heavy-duty hardware with wall options included.",
    tags: ["Event", "Popular", "Outdoor", "Custom"],
    sizes: ["10'×10'"],
    materials: ["Dye Sub Fabric Canopy"],
    sides: ["Full Print"],
    finishing: ["Full Walls","Half Walls","No Walls","Tent Accessories"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #166534 100%)",
    icon: "⛺",
    isNew: false,
    isFeatured: true
  },
  {
    id: "tent-002",
    name: "10x20 Event Tent",
    category: "Tents",
    subcategory: "Event Tents",
    description: "Larger 10x20 aluminum event tent for bigger footprints at trade shows and outdoor events.",
    tags: ["Event", "Outdoor", "Trade"],
    sizes: ["10'×20'"],
    materials: ["Dye Sub Fabric Canopy"],
    sides: ["Full Print"],
    finishing: ["Full Walls","Half Walls","No Walls"],
    gradient: "linear-gradient(135deg, #059669 0%, #065f46 100%)",
    icon: "🏕️",
    isNew: true,
    isFeatured: false
  },

  // ── TABLE THROWS ─────────────────────────────────────────
  {
    id: "tt-001",
    name: "Table Throw",
    category: "Table Throws",
    subcategory: "Fitted Throws",
    description: "Full-color dye sub printed table throw. 3-sided and 4-sided options for 4ft, 6ft, and 8ft tables.",
    tags: ["Event", "Trade", "Indoor"],
    sizes: ["4ft","6ft","8ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["3-Sided","4-Sided"],
    finishing: ["Machine Washable"],
    gradient: "linear-gradient(135deg, #9333ea 0%, #7e22ce 100%)",
    icon: "🛋️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "tt-002",
    name: "Stretch Table Throw",
    category: "Table Throws",
    subcategory: "Stretch Throws",
    description: "Fitted stretch table cover for a sleek, tailored look. Available for 6ft and 8ft tables.",
    tags: ["Event", "Trade", "Premium"],
    sizes: ["6ft","8ft"],
    materials: ["Stretch Dye Sub Fabric"],
    sides: ["Full Cover"],
    finishing: ["Machine Washable"],
    gradient: "linear-gradient(135deg, #c026d3 0%, #a21caf 100%)",
    icon: "🎪",
    isNew: false,
    isFeatured: false
  },
  {
    id: "tt-003",
    name: "Round Table Cover",
    category: "Table Throws",
    subcategory: "Round Covers",
    description: "Full-color printed round table covers for 31\", 36\", 48\", and 60\" diameter tables.",
    tags: ["Event", "Trade"],
    sizes: ["31\" Diameter","36\" Diameter","48\" Diameter","60\" Diameter"],
    materials: ["Dye Sub Fabric"],
    sides: ["Standard Height","Bar Height"],
    finishing: ["Machine Washable"],
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)",
    icon: "🍽️",
    isNew: true,
    isFeatured: false
  },

  // ── TRADE SHOW / SEG ─────────────────────────────────────
  {
    id: "seg-001",
    name: "Tension Fabric Display — Curved",
    category: "Trade Show",
    subcategory: "Tension Fabric Displays",
    description: "Curved tension fabric display for stunning backwall presence. Available in 6ft, 8ft, 10ft.",
    tags: ["Trade", "Event", "Popular"],
    sizes: ["6ft","8ft","10ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided"],
    finishing: ["LED Spotlights","Carry Case"],
    gradient: "linear-gradient(135deg, #1e40af 0%, #1e3a8a 100%)",
    icon: "🖼️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "seg-002",
    name: "Tension Fabric Display — Straight",
    category: "Trade Show",
    subcategory: "Tension Fabric Displays",
    description: "Straight tension fabric displays from 8ft to 20ft for large booth backwalls.",
    tags: ["Trade", "Event"],
    sizes: ["8ft","10ft","20ft"],
    materials: ["Dye Sub Fabric"],
    sides: ["Single Sided"],
    finishing: ["LED Spotlights","Carry Case"],
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e40af 100%)",
    icon: "📏",
    isNew: false,
    isFeatured: false
  },
  {
    id: "seg-003",
    name: "SEG Display — 3ft / 10ft / 20ft",
    category: "Trade Show",
    subcategory: "SEG Displays",
    description: "Silicon Edge Graphics (SEG) displays with extruded aluminum frame. UV printed fabric.",
    tags: ["Trade", "Event", "Premium"],
    sizes: ["3ft","10ft","20ft"],
    materials: ["UV Printed SEG Fabric"],
    sides: ["Single Sided"],
    finishing: ["Aluminum Frame","LED Backlit Option"],
    gradient: "linear-gradient(135deg, #0f766e 0%, #115e59 100%)",
    icon: "✨",
    isNew: false,
    isFeatured: true
  },
  {
    id: "seg-004",
    name: "SEG Backlit Popup Display",
    category: "Trade Show",
    subcategory: "SEG Backlit",
    description: "Backlit SEG popup display for maximum visual impact at trade shows. 8ft and 10ft sizes.",
    tags: ["Trade", "Backlit", "Premium"],
    sizes: ["8ft","10ft"],
    materials: ["SEG Backlit Fabric"],
    sides: ["Single Sided"],
    finishing: ["Backlit Frame","Carry Case"],
    gradient: "linear-gradient(135deg, #d97706 0%, #92400e 100%)",
    icon: "💎",
    isNew: true,
    isFeatured: false
  },
  {
    id: "seg-005",
    name: "Trade Show Booth Kit",
    category: "Trade Show",
    subcategory: "Booth Kits",
    description: "Complete trade show booth kit for 10' and 20' booths. Everything you need in one package.",
    tags: ["Trade", "Event", "Complete Kit"],
    sizes: ["10ft Booth","20ft Booth"],
    materials: ["Mixed"],
    sides: ["Custom"],
    finishing: ["All Hardware Included"],
    gradient: "linear-gradient(135deg, #374151 0%, #111827 100%)",
    icon: "🏪",
    isNew: false,
    isFeatured: false
  },

  // ── RIGID SIGNS ──────────────────────────────────────────
  {
    id: "rig-001",
    name: "Coroplast Sign",
    category: "Rigids",
    subcategory: "Rigid Signs",
    description: "Lightweight corrugated plastic signs. Ideal for yard signs, real estate, and temporary signage.",
    tags: ["Outdoor", "Popular", "Real Estate"],
    sizes: ["12\"×18\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["4mm Coroplast"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["H-Stake","Grommets","Rounded Corners","Straight Cut"],
    gradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    icon: "📋",
    isNew: false,
    isFeatured: false
  },
  {
    id: "rig-002",
    name: "Aluminum Sandwich Board Sign",
    category: "Rigids",
    subcategory: "Rigid Signs",
    description: "Rigid aluminum composite board sign for long-lasting indoor and outdoor use.",
    tags: ["Outdoor", "Durable"],
    sizes: ["12\"×18\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["1/8\" Aluminum Sandwich Board"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["Grommets","Drilled Holes","Rounded Corners"],
    gradient: "linear-gradient(135deg, #64748b 0%, #475569 100%)",
    icon: "🔲",
    isNew: false,
    isFeatured: false
  },
  {
    id: "rig-003",
    name: "PVC Board Sign",
    category: "Rigids",
    subcategory: "Rigid Signs",
    description: "Versatile 1/8\" white PVC board for indoor and outdoor signage with a clean finish.",
    tags: ["Indoor", "Outdoor"],
    sizes: ["12\"×18\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["1/8\" White PVC"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["Grommets","Rounded Corners","Drilled Holes"],
    gradient: "linear-gradient(135deg, #e2e8f0 0%, #cbd5e1 100%)",
    icon: "⬜",
    isNew: false,
    isFeatured: false
  },
  {
    id: "rig-004",
    name: "Foam Board Sign",
    category: "Rigids",
    subcategory: "Rigid Signs",
    description: "Lightweight 3/16\" white foam board for indoor displays, presentations, and events.",
    tags: ["Indoor", "Lightweight"],
    sizes: ["11\"×14\"","16\"×20\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["3/16\" Foam Board"],
    sides: ["Single Sided"],
    finishing: ["Straight Cut","Rounded Corners"],
    gradient: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
    icon: "📄",
    isNew: false,
    isFeatured: false
  },
  {
    id: "rig-005",
    name: "Vehicle Magnet",
    category: "Rigids",
    subcategory: "Magnets",
    description: "Full-color magnetic signs for vehicle doors. Easy on, easy off — no damage to paint.",
    tags: ["Outdoor", "Popular", "Vehicle"],
    sizes: ["12\"×18\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["Magnetic Material"],
    sides: ["Single Sided"],
    finishing: ["Rounded Corners","Straight Cut"],
    gradient: "linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)",
    icon: "🚗",
    isNew: false,
    isFeatured: true
  },
  {
    id: "rig-006",
    name: ".040 Aluminum Sign",
    category: "Rigids",
    subcategory: "Aluminum Signs",
    description: "Heavy-duty .040 aluminum signs for permanent outdoor use. Available in 3 sizes.",
    tags: ["Outdoor", "Durable", "Permanent"],
    sizes: ["12\"×18\"","18\"×24\"","24\"×36\""],
    materials: [".040 Aluminum"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["Grommets","Drilled Holes","Rounded Corners"],
    gradient: "linear-gradient(135deg, #6b7280 0%, #4b5563 100%)",
    icon: "🔩",
    isNew: false,
    isFeatured: false
  },

  // ── ADHESIVES ────────────────────────────────────────────
  {
    id: "adh-001",
    name: "Adhesive Vinyl (Calendered)",
    category: "Adhesives",
    subcategory: "Adhesive Films",
    description: "Pressure-sensitive calendered adhesive vinyl for walls, windows, and flat surfaces.",
    tags: ["Indoor", "Outdoor"],
    sizes: ["Custom Roll","Custom Cut"],
    materials: ["Calendered Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Standard Cut","Contour Cut"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #15803d 100%)",
    icon: "🖖",
    isNew: false,
    isFeatured: false
  },
  {
    id: "adh-002",
    name: "Premium Window Cling",
    category: "Adhesives",
    subcategory: "Window Graphics",
    description: "Static cling window film — no adhesive needed. Easy to apply and remove. Crystal clear.",
    tags: ["Indoor", "Window", "Removable"],
    sizes: ["Custom"],
    materials: ["Premium Window Cling Film"],
    sides: ["Single Sided"],
    finishing: ["Standard Cut","Contour Cut"],
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)",
    icon: "🪟",
    isNew: false,
    isFeatured: false
  },
  {
    id: "adh-003",
    name: "Adhesive Window Perf",
    category: "Adhesives",
    subcategory: "Window Graphics",
    description: "See-through perforated window vinyl. Print on outside, see through from inside.",
    tags: ["Outdoor", "Window"],
    sizes: ["Custom"],
    materials: ["Perforated Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Standard Cut"],
    gradient: "linear-gradient(135deg, #f97316 0%, #c2410c 100%)",
    icon: "👁️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "adh-004",
    name: "Reflective Adhesive Vinyl",
    category: "Adhesives",
    subcategory: "Reflective Films",
    description: "High-visibility reflective adhesive vinyl for safety signage, vehicles, and outdoor use.",
    tags: ["Outdoor", "Safety", "Reflective"],
    sizes: ["Custom Roll","Custom Cut"],
    materials: ["Reflective Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Standard Cut","Contour Cut"],
    gradient: "linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%)",
    icon: "🔆",
    isNew: false,
    isFeatured: false
  },
  {
    id: "adh-005",
    name: "Dry Erase Adhesive Vinyl",
    category: "Adhesives",
    subcategory: "Specialty Films",
    description: "Write-on, wipe-off dry erase adhesive vinyl. Apply to any flat surface for reusable messaging.",
    tags: ["Indoor", "Dry Erase", "Reusable"],
    sizes: ["Custom Roll","Custom Cut"],
    materials: ["Dry Erase Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Standard Cut"],
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    icon: "✏️",
    isNew: true,
    isFeatured: false
  },
  {
    id: "adh-006",
    name: "Floor Graphics",
    category: "Adhesives",
    subcategory: "Floor Films",
    description: "Anti-slip floor graphics for retail, events, and wayfinding. Laminated for foot traffic.",
    tags: ["Indoor", "Outdoor", "Wayfinding"],
    sizes: ["Custom"],
    materials: ["Floor Laminate Vinyl"],
    sides: ["Single Sided"],
    finishing: ["Anti-Slip Laminate"],
    gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    icon: "👣",
    isNew: true,
    isFeatured: false
  },

  // ── CHANNEL LETTERS ──────────────────────────────────────
  {
    id: "ch-001",
    name: "Standard Channel Letters",
    category: "Channel Letters",
    subcategory: "Illuminated Letters",
    description: "Front-lit channel letters with acrylic faces and trimcaps. Front-lit and dual-lit options. .040 aluminum returns.",
    tags: ["Outdoor", "Illuminated", "Custom", "Popular"],
    sizes: ["Custom"],
    materials: ["Acrylic Face",".040 Aluminum Returns"],
    sides: ["Front Lit","Dual Lit"],
    finishing: ["LED Illuminated","Raceway Mount","Direct Mount"],
    gradient: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    icon: "🔤",
    isNew: false,
    isFeatured: true
  },
  {
    id: "ch-002",
    name: "Halo / Reverse Lit Channel Letters",
    category: "Channel Letters",
    subcategory: "Illuminated Letters",
    description: "Halo-lit reverse channel letters with fabricated stainless steel faces. Elegant backlit glow effect.",
    tags: ["Outdoor", "Illuminated", "Premium"],
    sizes: ["Custom"],
    materials: ["Stainless Steel Face","Aluminum Returns"],
    sides: ["Reverse Lit / Halo"],
    finishing: ["LED Halo","Raceway Mount","Direct Mount"],
    gradient: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    icon: "✨",
    isNew: false,
    isFeatured: true
  },
  {
    id: "ch-003",
    name: "Premium Channel Letters",
    category: "Channel Letters",
    subcategory: "Illuminated Letters",
    description: "Premium channel letters with acrylic faces and fabricated welded stainless steel returns. Multiple return color options.",
    tags: ["Outdoor", "Illuminated", "Premium"],
    sizes: ["Custom"],
    materials: ["Acrylic Face","Fabricated Stainless Returns"],
    sides: ["Front Lit"],
    finishing: ["LED Illuminated","Multiple Return Colors"],
    gradient: "linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)",
    icon: "💠",
    isNew: false,
    isFeatured: false
  },

  // ── REAL ESTATE / OUTDOOR ────────────────────────────────
  {
    id: "re-001",
    name: "Yard Sign + H-Stake",
    category: "Real Estate Products",
    subcategory: "Yard Signs",
    description: "Double-sided coroplast yard sign with H-stake. Full-color printing for real estate and events.",
    tags: ["Outdoor", "Real Estate", "Popular"],
    sizes: ["18\"×24\"","24\"×36\""],
    materials: ["4mm Coroplast"],
    sides: ["Double Sided"],
    finishing: ["H-Stake Included"],
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e40af 100%)",
    icon: "🏡",
    isNew: false,
    isFeatured: false
  },
  {
    id: "re-002",
    name: "Deluxe Signicade A-Frame",
    category: "Real Estate Products",
    subcategory: "A-Frames",
    description: "Heavy-duty signicade A-frame with swinging sign holder. Black or white hardware with coroplast graphics.",
    tags: ["Outdoor", "A-Frame", "Real Estate"],
    sizes: ["22\"×28\""],
    materials: ["Coroplast Graphics","Vinyl Graphics"],
    sides: ["Double Sided"],
    finishing: ["Black Hardware","White Hardware"],
    gradient: "linear-gradient(135deg, #374151 0%, #1f2937 100%)",
    icon: "🅰️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "re-003",
    name: "PVC Post + Sign",
    category: "Real Estate Products",
    subcategory: "Post Systems",
    description: "Professional PVC post and sign system for real estate listings. Clean, modern look.",
    tags: ["Outdoor", "Real Estate"],
    sizes: ["Custom"],
    materials: ["PVC Post","Coroplast Sign"],
    sides: ["Double Sided"],
    finishing: ["Post Hardware Included"],
    gradient: "linear-gradient(135deg, #0369a1 0%, #075985 100%)",
    icon: "🏠",
    isNew: false,
    isFeatured: false
  },

  // ── DTF ──────────────────────────────────────────────────
  {
    id: "dtf-001",
    name: "DTF Transfer Printing",
    category: "DTF and UV DTF",
    subcategory: "DTF Transfers",
    description: "Direct-to-Film transfers for apparel, bags, and fabric. Vibrant full-color with soft hand feel.",
    tags: ["Popular", "Apparel", "Custom"],
    sizes: ["Custom Gang Sheet","Custom Size"],
    materials: ["DTF Transfer Film"],
    sides: ["Single Sided"],
    finishing: ["Ready to Press","Heat Transfer"],
    gradient: "linear-gradient(135deg, #be185d 0%, #9d174d 100%)",
    icon: "👕",
    isNew: false,
    isFeatured: true
  },
  {
    id: "dtf-002",
    name: "UV DTF Transfer",
    category: "DTF and UV DTF",
    subcategory: "UV DTF",
    description: "UV DTF transfers for hard surfaces — tumblers, phone cases, bottles, and more. No heat required.",
    tags: ["Popular", "Hard Surface", "Custom", "New"],
    sizes: ["Custom Gang Sheet","A4","Letter"],
    materials: ["UV DTF Film"],
    sides: ["Single Sided"],
    finishing: ["Peel & Apply"],
    gradient: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)",
    icon: "✨",
    isNew: true,
    isFeatured: true
  },

  // ── WALL ART / CANVAS ────────────────────────────────────
  {
    id: "wall-001",
    name: "Framed Canvas Print",
    category: "Wall Art",
    subcategory: "Canvas",
    description: "Museum-quality framed canvas prints. Arrive ready to hang with a sturdy wood frame.",
    tags: ["Indoor", "Premium", "Decor"],
    sizes: ["8\"×10\"","11\"×14\"","16\"×20\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["Canvas","Wood Frame"],
    sides: ["Single Sided"],
    finishing: ["Black Frame","White Frame","Natural Wood"],
    gradient: "linear-gradient(135deg, #92400e 0%, #78350f 100%)",
    icon: "🖼️",
    isNew: false,
    isFeatured: false
  },
  {
    id: "wall-002",
    name: "Stretched Canvas Print",
    category: "Wall Art",
    subcategory: "Canvas",
    description: "Gallery-wrapped stretched canvas prints on solid wood stretcher bars. Ready to display.",
    tags: ["Indoor", "Decor", "Popular"],
    sizes: ["8\"×10\"","12\"×16\"","16\"×20\"","20\"×24\"","24\"×30\"","Custom"],
    materials: ["Canvas","Wood Stretcher Bars"],
    sides: ["Gallery Wrap"],
    finishing: ["Gallery Wrap","Mirrored Wrap","White Border"],
    gradient: "linear-gradient(135deg, #b45309 0%, #92400e 100%)",
    icon: "🎨",
    isNew: false,
    isFeatured: false
  },
  {
    id: "wall-003",
    name: "Wall Mural / Adhesive Wall Fabric",
    category: "Wall Art",
    subcategory: "Wall Murals",
    description: "Removable adhesive wall fabric murals for offices, retail, and events. Easy to apply and remove.",
    tags: ["Indoor", "Removable", "Large Format"],
    sizes: ["Custom"],
    materials: ["Adhesive Wall Fabric"],
    sides: ["Single Sided"],
    finishing: ["Repositionable Adhesive"],
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    icon: "🏛️",
    isNew: true,
    isFeatured: false
  },

  // ── POSTERS / LARGE FORMAT ───────────────────────────────
  {
    id: "pst-001",
    name: "Poster Print",
    category: "Posters",
    subcategory: "Posters",
    description: "High-quality poster printing on gloss or matte paper. Great for events, menus, and promotions.",
    tags: ["Indoor", "Popular"],
    sizes: ["11\"×17\"","18\"×24\"","24\"×36\"","Custom"],
    materials: ["Gloss Paper","Matte Paper","Satin Paper"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["None","Lamination","Foam Board Mount"],
    gradient: "linear-gradient(135deg, #db2777 0%, #be185d 100%)",
    icon: "📰",
    isNew: false,
    isFeatured: false
  },
  {
    id: "lf-001",
    name: "Large Format Print",
    category: "Large Format",
    subcategory: "Large Format",
    description: "Custom large format printing on a wide variety of substrates. Virtually any size up to 16ft wide.",
    tags: ["Outdoor", "Indoor", "Custom", "Large Format"],
    sizes: ["Up to 16ft wide","Custom Length"],
    materials: ["Vinyl","Fabric","Canvas","Paper","Custom"],
    sides: ["Single Sided","Double Sided"],
    finishing: ["Hem","Grommets","Poles","Custom"],
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%)",
    icon: "📐",
    isNew: false,
    isFeatured: false
  }
];

// ── CATEGORY CONFIG ──────────────────────────────────────────
const CATEGORIES = [
  { id: "all", name: "All Products", icon: "🗂️", color: "#1e3a8a" },
  { id: "Banners", name: "Banners", icon: "🏷️", color: "#d97706", sub: ["Vinyl Banners","Fabric Banners","Pole Banners","Specialty Banners"] },
  { id: "Flags", name: "Flags", icon: "🏴", color: "#dc2626", sub: ["Advertising Flags","Pole Flags"] },
  { id: "Banner Stands", name: "Banner Stands", icon: "📐", color: "#7c3aed", sub: ["Retractable Stands","Fabric Stands","X-Stands","Backdrops","Table Top Displays"] },
  { id: "Trade Show", name: "Trade Show", icon: "🏪", color: "#0369a1", sub: ["Tension Fabric Displays","SEG Displays","SEG Backlit","Booth Kits"] },
  { id: "Tents", name: "Tents", icon: "⛺", color: "#16a34a", sub: ["Event Tents"] },
  { id: "Table Throws", name: "Table Throws", icon: "🛋️", color: "#9333ea", sub: ["Fitted Throws","Stretch Throws","Round Covers"] },
  { id: "Rigids", name: "Rigids", icon: "🔲", color: "#64748b", sub: ["Rigid Signs","Magnets","Aluminum Signs"] },
  { id: "Adhesives", name: "Adhesives", icon: "🖖", color: "#059669", sub: ["Adhesive Films","Window Graphics","Reflective Films","Specialty Films","Floor Films"] },
  { id: "Wall Art", name: "Wall Art", icon: "🖼️", color: "#b45309", sub: ["Canvas","Wall Murals"] },
  { id: "Channel Letters", name: "Channel Letters", icon: "🔤", color: "#f97316", sub: ["Illuminated Letters"] },
  { id: "DTF and UV DTF", name: "DTF & UV DTF", icon: "👕", color: "#be185d", sub: ["DTF Transfers","UV DTF"] },
  { id: "Real Estate Products", name: "Real Estate", icon: "🏡", color: "#1d4ed8", sub: ["Yard Signs","A-Frames","Post Systems"] },
  { id: "Posters", name: "Posters", icon: "📰", color: "#db2777", sub: [] },
  { id: "Large Format", name: "Large Format", icon: "📐", color: "#1e3a8a", sub: [] }
];
